### PR TITLE
feat: Manage mirror volumes

### PR DESCRIPTION
**Pull request by nladuguie**

### CODE REVIEW

**Comment by nladuguie** [comment]
Refers to issue #53

**Comment by devproof** [comment]
Thanks for pull request.
What do you think about renaming source field into mirror_volume_source? This would be more clear.

**Comment by nladuguie** [comment]
Hi @devproof , good idea about the renaming, and it is already pushed inside my branch.
Please review and validate if it is correct.

**Comment by nladuguie** [comment]
I have changed the way we manage the mirror schedule in order to provide the schedule name instead of his ID to be more flexible, like the snapshot schedule works.

**Comment by devproof** [comment]
I need some time to merge it, since I'm focussing on MapR 6. uplift.

**Pull request merged**
